<?php
/* RUTA SERVIDOR*/
/*define("RUTA", './'); */

/*RUTA LOCAL */
define("RUTA", '/proyectoFinal/web/');


/*NOTAS IMPORTANTES PARA LA PUBLICACION WEBSITE */
/* EN ESTE ARCHIVO CONFIG.PHP HAY QUE DESCOMENTAR LA RUTA DEL SERVIDOR Y COMENTAR LA RUTA LOCAL */
/* EN EL ARCHIVO APP/MODELS/CONEXIONBD.PHP HAY QUE COMENTAR LA RUTA DEL SERVIDOR Y DESCOMENTAR LA RUTA LOCAL */